package view;

public enum Evento {
	LOGIN, RES_LOGIN_OK, RES_LOGIN_KO,

	REGISTER, RES_REGISTER_OK, RES_REGISTER_KO,

	LOGOUT, RES_LOGOUT_OK,

	GUI_UPLOAD, UPLOAD_FILES, RES_UPLOAD_OK, RES_UPLOAD_KO,

	LIST_FILES, RES_LIST_OK, RES_LIST_KO,

	GUI_DOWNLOAD, DOWNLOAD_FILES, RES_DOWNLOAD_OK, RES_DOWNLOAD_KO,

	LIST_USERS, RES_LIST_USERS_OK, RES_LIST_USERS_KO, GUI_LIST,

}